version: "3"

services:
  app1:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - EULA=true
      - VIRTUAL_HOST=app1.EXAMPLE.NET
      - LETSENCRYPT_HOST=app1.EXAMPLE.NET
      - LETSENCRYPT_EMAIL=app1@EXAMPLE.NET
    ports:
      - "80"

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
